# Generated by Django 3.2.6 on 2021-10-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20211006_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='host',
            new_name='ip',
        ),
    ]
