# Generated by Django 3.2.6 on 2021-10-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20211006_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='host',
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='ip',
        ),
    ]
